import 'package:home_bite/models/food_items_datastructure.dart';


const fooditems  = [
  FoodDataStructure(
    foodname: 'Dal Makhani',
    price: 150,
    rating: 4.8,
    cookName: 'Mrs. Sharma',
    location: 'Kitchen 1',
    imageurl: 'assets/images/snacks.jpg',
  ),
  FoodDataStructure(
    foodname: 'Paneer Tikka',
    price: 120,
    rating: 4.5,
    cookName: 'Mr. Verma',
    location: 'Kitchen 2',
    imageurl: 'assets/images/paneer_tikka.jpg',
  ),
  FoodDataStructure(
    foodname: 'Aloo Paratha',
    price: 100,
    rating: 4.7,
    cookName: 'Mrs. Kapoor',
    location: 'Kitchen 1',
    imageurl: 'assets/images/aloo_paratha.jpg',
  ),
  FoodDataStructure(
    foodname: 'Butter Chicken',
    price: 180,
    rating: 4.9,
    cookName: 'Mr. Singh',
    location: 'Kitchen 2',
    imageurl: 'assets/images/butter_chicken.jpg',
  ),
  FoodDataStructure(
    foodname: 'Rajma Chawal',
    price: 130,
    rating: 4.6,
    cookName: 'Mrs. Gupta',
    location: 'Kitchen 1',
    imageurl: 'assets/images/rajma_chawal.jpg',
  ),
  FoodDataStructure(
    foodname: 'Chole Bhature',
    price: 110,
    rating: 4.5,
    cookName: 'Mr. Sharma',
    location: 'Kitchen 2',
    imageurl: 'assets/images/chole_bhature.jpg',
  ),
  FoodDataStructure(
    foodname: 'Palak Paneer',
    price: 160,
    rating: 4.7,
    cookName: 'Mrs. Verma',
    location: 'Kitchen 1',
    imageurl: 'assets/images/palak_paneer.jpg',
  ),
  FoodDataStructure(
    foodname: 'Samosa',
    price: 80,
    rating: 4.4,
    cookName: 'Mr. Kapoor',
    location: 'Kitchen 2',
    imageurl: 'assets/images/samosa.jpg',
  ),
  FoodDataStructure(
    foodname: 'Biryani',
    price: 200,
    rating: 4.9,
    cookName: 'Mrs. Singh',
    location: 'Kitchen 1',
    imageurl: 'assets/images/biryani.jpg',
  ),
  FoodDataStructure(
    foodname: 'Gulab Jamun',
    price: 60,
    rating: 4.6,
    cookName: 'Mr. Gupta',
    location: 'Kitchen 2',
    imageurl: 'assets/images/gulab_jamun.jpg',
  ),
];