// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Y-cfGJRUivj6Hmm0By3e85fFIUjWCSU',
    appId: '1:305586759008:web:882dff508bc91cb34e2a05',
    messagingSenderId: '305586759008',
    projectId: 'homebite-c8f7c',
    authDomain: 'homebite-c8f7c.firebaseapp.com',
    storageBucket: 'homebite-c8f7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAdWGpGkiIQ290iXS7vYif0TEl96TtMOI',
    appId: '1:305586759008:android:a8cbe52fb6bd5c494e2a05',
    messagingSenderId: '305586759008',
    projectId: 'homebite-c8f7c',
    storageBucket: 'homebite-c8f7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeWB99RJoh_bHpfKbhy6SCKe22pDnQC1U',
    appId: '1:305586759008:ios:a3abfd14f61ee8584e2a05',
    messagingSenderId: '305586759008',
    projectId: 'homebite-c8f7c',
    storageBucket: 'homebite-c8f7c.appspot.com',
    iosBundleId: 'com.example.homeBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeWB99RJoh_bHpfKbhy6SCKe22pDnQC1U',
    appId: '1:305586759008:ios:ad4e9cf34233169f4e2a05',
    messagingSenderId: '305586759008',
    projectId: 'homebite-c8f7c',
    storageBucket: 'homebite-c8f7c.appspot.com',
    iosBundleId: 'com.example.homeBite.RunnerTests',
  );
}
